### PR TITLE
FIX+ENH: Gradient coeff + MSMSulc full support

### PR DESCRIPTION
**Pull request by mgxd**
Changes
- `Dockerfile`
  - change OS to jessie (stretch's `perl` incompatible with FS5.3)
  - include `gradunwarp` and later version of `libstdc++6` (needed for MSMSulc)
  - recipe cleanup
- `run.py`
  - new option for scanner gradients coeff file (for image unwarping)
  - properly extract BOLD fieldmap phase encodings

### CODE REVIEW

**Comment by chrisfilo** [comment]
Thanks for sending the PR! I'm seeing 
```
Traceback (most recent call last):

  File "/run.py", line 213, in <module>

    layout = BIDSLayout(args.bids_dir, exclude=['derivatives'])

  File "/usr/local/miniconda/lib/python2.7/site-packages/bids/grabbids/bids_layout.py", line 103, in __init__

    exclude=exclude, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'config'
``` 
on Circle

**Comment by mgxd** [comment]
@chrisfilo looks like a mismatch with pybids, as `config` was removed in 0.6+. however i'm not sure why this is happening, since we're pinning `pybids==0.5.1` ...

FWIW, i was able to successfully run the pipeline within a singularity image, so it may be circle specific (maybe we should update circle to 2.0?)

**Comment by chrisfilo** [comment]
Maybe we need to pin grabbits as well?

(indeed we need to switch to circle 2.0, but this is probably unrelated)

**Comment by mgxd** [comment]
@chrisfilo this can close #33 #32

**Comment by chrisfilo** [comment]
Fantastic work - thanks!

**Pull request merged**
